# Generated by Django 5.0.6 on 2024-06-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_shipper_techicalmachine_warehouse_goods_stocktaking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('pay_method', models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('sbp', 'СБП')], default='cash', max_length=20)),
                ('client_info', models.TextField()),
                ('extraservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_extraservice', to='task_manager.extraservice')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_tour', to='task_manager.tour')),
            ],
        ),
    ]
