# Generated by Django 5.0.6 on 2024-06-26 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_tourist_alter_booking_client_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='client_info',
        ),
        migrations.AddField(
            model_name='booking',
            name='tourist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='booking_tourist', to='task_manager.tourist'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='zip_code',
            field=models.IntegerField(default='1'),
        ),
    ]
