# Generated by Django 5.0.6 on 2024-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0009_remove_booking_client_info_booking_tourist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default='2024-02-10'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default='2024-03-10'),
        ),
    ]
