# Generated by Django 5.0.6 on 2024-06-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0010_booking_end_date_booking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tourist',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_tourist', to='task_manager.tourist'),
        ),
    ]
