# Generated by Django 5.0.6 on 2024-06-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0011_alter_booking_tourist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='extraservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_extraservice', to='task_manager.extraservice'),
        ),
    ]
