# Generated by Django 5.0.6 on 2024-06-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourist',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
