# Generated by Django 5.0.6 on 2024-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_phone_number_tourist_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
